/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as QuizNewRouteImport } from './routes/quiz/new'
import { Route as GamesGameTypeRouteImport } from './routes/games/$gameType'
import { Route as BackgammonNewRouteImport } from './routes/backgammon/new'
import { Route as BackgammonSessionIdRouteImport } from './routes/backgammon/$sessionId'
import { Route as QuizSessionIdPlayRouteImport } from './routes/quiz/$sessionId/play'
import { Route as QuizSessionIdHostRouteImport } from './routes/quiz/$sessionId/host'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizNewRoute = QuizNewRouteImport.update({
  id: '/quiz/new',
  path: '/quiz/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameTypeRoute = GamesGameTypeRouteImport.update({
  id: '/games/$gameType',
  path: '/games/$gameType',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgammonNewRoute = BackgammonNewRouteImport.update({
  id: '/backgammon/new',
  path: '/backgammon/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgammonSessionIdRoute = BackgammonSessionIdRouteImport.update({
  id: '/backgammon/$sessionId',
  path: '/backgammon/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSessionIdPlayRoute = QuizSessionIdPlayRouteImport.update({
  id: '/quiz/$sessionId/play',
  path: '/quiz/$sessionId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSessionIdHostRoute = QuizSessionIdHostRouteImport.update({
  id: '/quiz/$sessionId/host',
  path: '/quiz/$sessionId/host',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/backgammon/$sessionId': typeof BackgammonSessionIdRoute
  '/backgammon/new': typeof BackgammonNewRoute
  '/games/$gameType': typeof GamesGameTypeRoute
  '/quiz/new': typeof QuizNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/quiz/$sessionId/host': typeof QuizSessionIdHostRoute
  '/quiz/$sessionId/play': typeof QuizSessionIdPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/backgammon/$sessionId': typeof BackgammonSessionIdRoute
  '/backgammon/new': typeof BackgammonNewRoute
  '/games/$gameType': typeof GamesGameTypeRoute
  '/quiz/new': typeof QuizNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/quiz/$sessionId/host': typeof QuizSessionIdHostRoute
  '/quiz/$sessionId/play': typeof QuizSessionIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/backgammon/$sessionId': typeof BackgammonSessionIdRoute
  '/backgammon/new': typeof BackgammonNewRoute
  '/games/$gameType': typeof GamesGameTypeRoute
  '/quiz/new': typeof QuizNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/quiz/$sessionId/host': typeof QuizSessionIdHostRoute
  '/quiz/$sessionId/play': typeof QuizSessionIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/join'
    | '/backgammon/$sessionId'
    | '/backgammon/new'
    | '/games/$gameType'
    | '/quiz/new'
    | '/dashboard/'
    | '/quiz/$sessionId/host'
    | '/quiz/$sessionId/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/join'
    | '/backgammon/$sessionId'
    | '/backgammon/new'
    | '/games/$gameType'
    | '/quiz/new'
    | '/dashboard'
    | '/quiz/$sessionId/host'
    | '/quiz/$sessionId/play'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/join'
    | '/backgammon/$sessionId'
    | '/backgammon/new'
    | '/games/$gameType'
    | '/quiz/new'
    | '/dashboard/'
    | '/quiz/$sessionId/host'
    | '/quiz/$sessionId/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JoinRoute: typeof JoinRoute
  BackgammonSessionIdRoute: typeof BackgammonSessionIdRoute
  BackgammonNewRoute: typeof BackgammonNewRoute
  GamesGameTypeRoute: typeof GamesGameTypeRoute
  QuizNewRoute: typeof QuizNewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  QuizSessionIdHostRoute: typeof QuizSessionIdHostRoute
  QuizSessionIdPlayRoute: typeof QuizSessionIdPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/new': {
      id: '/quiz/new'
      path: '/quiz/new'
      fullPath: '/quiz/new'
      preLoaderRoute: typeof QuizNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameType': {
      id: '/games/$gameType'
      path: '/games/$gameType'
      fullPath: '/games/$gameType'
      preLoaderRoute: typeof GamesGameTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgammon/new': {
      id: '/backgammon/new'
      path: '/backgammon/new'
      fullPath: '/backgammon/new'
      preLoaderRoute: typeof BackgammonNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgammon/$sessionId': {
      id: '/backgammon/$sessionId'
      path: '/backgammon/$sessionId'
      fullPath: '/backgammon/$sessionId'
      preLoaderRoute: typeof BackgammonSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$sessionId/play': {
      id: '/quiz/$sessionId/play'
      path: '/quiz/$sessionId/play'
      fullPath: '/quiz/$sessionId/play'
      preLoaderRoute: typeof QuizSessionIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$sessionId/host': {
      id: '/quiz/$sessionId/host'
      path: '/quiz/$sessionId/host'
      fullPath: '/quiz/$sessionId/host'
      preLoaderRoute: typeof QuizSessionIdHostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JoinRoute: JoinRoute,
  BackgammonSessionIdRoute: BackgammonSessionIdRoute,
  BackgammonNewRoute: BackgammonNewRoute,
  GamesGameTypeRoute: GamesGameTypeRoute,
  QuizNewRoute: QuizNewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  QuizSessionIdHostRoute: QuizSessionIdHostRoute,
  QuizSessionIdPlayRoute: QuizSessionIdPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
