/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordLinksIndexRouteImport } from './routes/word-links/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as WordLinksPuzzleIdRouteImport } from './routes/word-links/$puzzleId'
import { Route as SudokuScanRouteImport } from './routes/sudoku/scan'
import { Route as SudokuNewRouteImport } from './routes/sudoku/new'
import { Route as SudokuSessionIdRouteImport } from './routes/sudoku/$sessionId'
import { Route as SignalWordsNewRouteImport } from './routes/signal-words/new'
import { Route as SignalWordsSessionIdRouteImport } from './routes/signal-words/$sessionId'
import { Route as QuizNewRouteImport } from './routes/quiz/new'
import { Route as HitsterNewRouteImport } from './routes/hitster/new'
import { Route as GamesGameTypeRouteImport } from './routes/games/$gameType'
import { Route as ConnectFourNewRouteImport } from './routes/connect-four/new'
import { Route as ConnectFourSessionIdRouteImport } from './routes/connect-four/$sessionId'
import { Route as ChessNewRouteImport } from './routes/chess/new'
import { Route as ChessSessionIdRouteImport } from './routes/chess/$sessionId'
import { Route as BackgammonNewRouteImport } from './routes/backgammon/new'
import { Route as BackgammonLocalRouteImport } from './routes/backgammon/local'
import { Route as BackgammonSessionIdRouteImport } from './routes/backgammon/$sessionId'
import { Route as QuizSessionIdPlayRouteImport } from './routes/quiz/$sessionId/play'
import { Route as QuizSessionIdHostRouteImport } from './routes/quiz/$sessionId/host'
import { Route as HitsterSessionIdPlayRouteImport } from './routes/hitster/$sessionId/play'
import { Route as HitsterSessionIdHostRouteImport } from './routes/hitster/$sessionId/host'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordLinksIndexRoute = WordLinksIndexRouteImport.update({
  id: '/word-links/',
  path: '/word-links/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordLinksPuzzleIdRoute = WordLinksPuzzleIdRouteImport.update({
  id: '/word-links/$puzzleId',
  path: '/word-links/$puzzleId',
  getParentRoute: () => rootRouteImport,
} as any)
const SudokuScanRoute = SudokuScanRouteImport.update({
  id: '/sudoku/scan',
  path: '/sudoku/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SudokuNewRoute = SudokuNewRouteImport.update({
  id: '/sudoku/new',
  path: '/sudoku/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SudokuSessionIdRoute = SudokuSessionIdRouteImport.update({
  id: '/sudoku/$sessionId',
  path: '/sudoku/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalWordsNewRoute = SignalWordsNewRouteImport.update({
  id: '/signal-words/new',
  path: '/signal-words/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalWordsSessionIdRoute = SignalWordsSessionIdRouteImport.update({
  id: '/signal-words/$sessionId',
  path: '/signal-words/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizNewRoute = QuizNewRouteImport.update({
  id: '/quiz/new',
  path: '/quiz/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HitsterNewRoute = HitsterNewRouteImport.update({
  id: '/hitster/new',
  path: '/hitster/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameTypeRoute = GamesGameTypeRouteImport.update({
  id: '/games/$gameType',
  path: '/games/$gameType',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectFourNewRoute = ConnectFourNewRouteImport.update({
  id: '/connect-four/new',
  path: '/connect-four/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectFourSessionIdRoute = ConnectFourSessionIdRouteImport.update({
  id: '/connect-four/$sessionId',
  path: '/connect-four/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessNewRoute = ChessNewRouteImport.update({
  id: '/chess/new',
  path: '/chess/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessSessionIdRoute = ChessSessionIdRouteImport.update({
  id: '/chess/$sessionId',
  path: '/chess/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgammonNewRoute = BackgammonNewRouteImport.update({
  id: '/backgammon/new',
  path: '/backgammon/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgammonLocalRoute = BackgammonLocalRouteImport.update({
  id: '/backgammon/local',
  path: '/backgammon/local',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgammonSessionIdRoute = BackgammonSessionIdRouteImport.update({
  id: '/backgammon/$sessionId',
  path: '/backgammon/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSessionIdPlayRoute = QuizSessionIdPlayRouteImport.update({
  id: '/quiz/$sessionId/play',
  path: '/quiz/$sessionId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSessionIdHostRoute = QuizSessionIdHostRouteImport.update({
  id: '/quiz/$sessionId/host',
  path: '/quiz/$sessionId/host',
  getParentRoute: () => rootRouteImport,
} as any)
const HitsterSessionIdPlayRoute = HitsterSessionIdPlayRouteImport.update({
  id: '/hitster/$sessionId/play',
  path: '/hitster/$sessionId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const HitsterSessionIdHostRoute = HitsterSessionIdHostRouteImport.update({
  id: '/hitster/$sessionId/host',
  path: '/hitster/$sessionId/host',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/backgammon/$sessionId': typeof BackgammonSessionIdRoute
  '/backgammon/local': typeof BackgammonLocalRoute
  '/backgammon/new': typeof BackgammonNewRoute
  '/chess/$sessionId': typeof ChessSessionIdRoute
  '/chess/new': typeof ChessNewRoute
  '/connect-four/$sessionId': typeof ConnectFourSessionIdRoute
  '/connect-four/new': typeof ConnectFourNewRoute
  '/games/$gameType': typeof GamesGameTypeRoute
  '/hitster/new': typeof HitsterNewRoute
  '/quiz/new': typeof QuizNewRoute
  '/signal-words/$sessionId': typeof SignalWordsSessionIdRoute
  '/signal-words/new': typeof SignalWordsNewRoute
  '/sudoku/$sessionId': typeof SudokuSessionIdRoute
  '/sudoku/new': typeof SudokuNewRoute
  '/sudoku/scan': typeof SudokuScanRoute
  '/word-links/$puzzleId': typeof WordLinksPuzzleIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/word-links/': typeof WordLinksIndexRoute
  '/hitster/$sessionId/host': typeof HitsterSessionIdHostRoute
  '/hitster/$sessionId/play': typeof HitsterSessionIdPlayRoute
  '/quiz/$sessionId/host': typeof QuizSessionIdHostRoute
  '/quiz/$sessionId/play': typeof QuizSessionIdPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/backgammon/$sessionId': typeof BackgammonSessionIdRoute
  '/backgammon/local': typeof BackgammonLocalRoute
  '/backgammon/new': typeof BackgammonNewRoute
  '/chess/$sessionId': typeof ChessSessionIdRoute
  '/chess/new': typeof ChessNewRoute
  '/connect-four/$sessionId': typeof ConnectFourSessionIdRoute
  '/connect-four/new': typeof ConnectFourNewRoute
  '/games/$gameType': typeof GamesGameTypeRoute
  '/hitster/new': typeof HitsterNewRoute
  '/quiz/new': typeof QuizNewRoute
  '/signal-words/$sessionId': typeof SignalWordsSessionIdRoute
  '/signal-words/new': typeof SignalWordsNewRoute
  '/sudoku/$sessionId': typeof SudokuSessionIdRoute
  '/sudoku/new': typeof SudokuNewRoute
  '/sudoku/scan': typeof SudokuScanRoute
  '/word-links/$puzzleId': typeof WordLinksPuzzleIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/word-links': typeof WordLinksIndexRoute
  '/hitster/$sessionId/host': typeof HitsterSessionIdHostRoute
  '/hitster/$sessionId/play': typeof HitsterSessionIdPlayRoute
  '/quiz/$sessionId/host': typeof QuizSessionIdHostRoute
  '/quiz/$sessionId/play': typeof QuizSessionIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/backgammon/$sessionId': typeof BackgammonSessionIdRoute
  '/backgammon/local': typeof BackgammonLocalRoute
  '/backgammon/new': typeof BackgammonNewRoute
  '/chess/$sessionId': typeof ChessSessionIdRoute
  '/chess/new': typeof ChessNewRoute
  '/connect-four/$sessionId': typeof ConnectFourSessionIdRoute
  '/connect-four/new': typeof ConnectFourNewRoute
  '/games/$gameType': typeof GamesGameTypeRoute
  '/hitster/new': typeof HitsterNewRoute
  '/quiz/new': typeof QuizNewRoute
  '/signal-words/$sessionId': typeof SignalWordsSessionIdRoute
  '/signal-words/new': typeof SignalWordsNewRoute
  '/sudoku/$sessionId': typeof SudokuSessionIdRoute
  '/sudoku/new': typeof SudokuNewRoute
  '/sudoku/scan': typeof SudokuScanRoute
  '/word-links/$puzzleId': typeof WordLinksPuzzleIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/word-links/': typeof WordLinksIndexRoute
  '/hitster/$sessionId/host': typeof HitsterSessionIdHostRoute
  '/hitster/$sessionId/play': typeof HitsterSessionIdPlayRoute
  '/quiz/$sessionId/host': typeof QuizSessionIdHostRoute
  '/quiz/$sessionId/play': typeof QuizSessionIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/forgot-password'
    | '/join'
    | '/sign-in'
    | '/sign-up'
    | '/backgammon/$sessionId'
    | '/backgammon/local'
    | '/backgammon/new'
    | '/chess/$sessionId'
    | '/chess/new'
    | '/connect-four/$sessionId'
    | '/connect-four/new'
    | '/games/$gameType'
    | '/hitster/new'
    | '/quiz/new'
    | '/signal-words/$sessionId'
    | '/signal-words/new'
    | '/sudoku/$sessionId'
    | '/sudoku/new'
    | '/sudoku/scan'
    | '/word-links/$puzzleId'
    | '/dashboard/'
    | '/word-links/'
    | '/hitster/$sessionId/host'
    | '/hitster/$sessionId/play'
    | '/quiz/$sessionId/host'
    | '/quiz/$sessionId/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/forgot-password'
    | '/join'
    | '/sign-in'
    | '/sign-up'
    | '/backgammon/$sessionId'
    | '/backgammon/local'
    | '/backgammon/new'
    | '/chess/$sessionId'
    | '/chess/new'
    | '/connect-four/$sessionId'
    | '/connect-four/new'
    | '/games/$gameType'
    | '/hitster/new'
    | '/quiz/new'
    | '/signal-words/$sessionId'
    | '/signal-words/new'
    | '/sudoku/$sessionId'
    | '/sudoku/new'
    | '/sudoku/scan'
    | '/word-links/$puzzleId'
    | '/dashboard'
    | '/word-links'
    | '/hitster/$sessionId/host'
    | '/hitster/$sessionId/play'
    | '/quiz/$sessionId/host'
    | '/quiz/$sessionId/play'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/forgot-password'
    | '/join'
    | '/sign-in'
    | '/sign-up'
    | '/backgammon/$sessionId'
    | '/backgammon/local'
    | '/backgammon/new'
    | '/chess/$sessionId'
    | '/chess/new'
    | '/connect-four/$sessionId'
    | '/connect-four/new'
    | '/games/$gameType'
    | '/hitster/new'
    | '/quiz/new'
    | '/signal-words/$sessionId'
    | '/signal-words/new'
    | '/sudoku/$sessionId'
    | '/sudoku/new'
    | '/sudoku/scan'
    | '/word-links/$puzzleId'
    | '/dashboard/'
    | '/word-links/'
    | '/hitster/$sessionId/host'
    | '/hitster/$sessionId/play'
    | '/quiz/$sessionId/host'
    | '/quiz/$sessionId/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  BackgammonSessionIdRoute: typeof BackgammonSessionIdRoute
  BackgammonLocalRoute: typeof BackgammonLocalRoute
  BackgammonNewRoute: typeof BackgammonNewRoute
  ChessSessionIdRoute: typeof ChessSessionIdRoute
  ChessNewRoute: typeof ChessNewRoute
  ConnectFourSessionIdRoute: typeof ConnectFourSessionIdRoute
  ConnectFourNewRoute: typeof ConnectFourNewRoute
  GamesGameTypeRoute: typeof GamesGameTypeRoute
  HitsterNewRoute: typeof HitsterNewRoute
  QuizNewRoute: typeof QuizNewRoute
  SignalWordsSessionIdRoute: typeof SignalWordsSessionIdRoute
  SignalWordsNewRoute: typeof SignalWordsNewRoute
  SudokuSessionIdRoute: typeof SudokuSessionIdRoute
  SudokuNewRoute: typeof SudokuNewRoute
  SudokuScanRoute: typeof SudokuScanRoute
  WordLinksPuzzleIdRoute: typeof WordLinksPuzzleIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  WordLinksIndexRoute: typeof WordLinksIndexRoute
  HitsterSessionIdHostRoute: typeof HitsterSessionIdHostRoute
  HitsterSessionIdPlayRoute: typeof HitsterSessionIdPlayRoute
  QuizSessionIdHostRoute: typeof QuizSessionIdHostRoute
  QuizSessionIdPlayRoute: typeof QuizSessionIdPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-links/': {
      id: '/word-links/'
      path: '/word-links'
      fullPath: '/word-links/'
      preLoaderRoute: typeof WordLinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-links/$puzzleId': {
      id: '/word-links/$puzzleId'
      path: '/word-links/$puzzleId'
      fullPath: '/word-links/$puzzleId'
      preLoaderRoute: typeof WordLinksPuzzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sudoku/scan': {
      id: '/sudoku/scan'
      path: '/sudoku/scan'
      fullPath: '/sudoku/scan'
      preLoaderRoute: typeof SudokuScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sudoku/new': {
      id: '/sudoku/new'
      path: '/sudoku/new'
      fullPath: '/sudoku/new'
      preLoaderRoute: typeof SudokuNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sudoku/$sessionId': {
      id: '/sudoku/$sessionId'
      path: '/sudoku/$sessionId'
      fullPath: '/sudoku/$sessionId'
      preLoaderRoute: typeof SudokuSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-words/new': {
      id: '/signal-words/new'
      path: '/signal-words/new'
      fullPath: '/signal-words/new'
      preLoaderRoute: typeof SignalWordsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-words/$sessionId': {
      id: '/signal-words/$sessionId'
      path: '/signal-words/$sessionId'
      fullPath: '/signal-words/$sessionId'
      preLoaderRoute: typeof SignalWordsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/new': {
      id: '/quiz/new'
      path: '/quiz/new'
      fullPath: '/quiz/new'
      preLoaderRoute: typeof QuizNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hitster/new': {
      id: '/hitster/new'
      path: '/hitster/new'
      fullPath: '/hitster/new'
      preLoaderRoute: typeof HitsterNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameType': {
      id: '/games/$gameType'
      path: '/games/$gameType'
      fullPath: '/games/$gameType'
      preLoaderRoute: typeof GamesGameTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-four/new': {
      id: '/connect-four/new'
      path: '/connect-four/new'
      fullPath: '/connect-four/new'
      preLoaderRoute: typeof ConnectFourNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-four/$sessionId': {
      id: '/connect-four/$sessionId'
      path: '/connect-four/$sessionId'
      fullPath: '/connect-four/$sessionId'
      preLoaderRoute: typeof ConnectFourSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess/new': {
      id: '/chess/new'
      path: '/chess/new'
      fullPath: '/chess/new'
      preLoaderRoute: typeof ChessNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess/$sessionId': {
      id: '/chess/$sessionId'
      path: '/chess/$sessionId'
      fullPath: '/chess/$sessionId'
      preLoaderRoute: typeof ChessSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgammon/new': {
      id: '/backgammon/new'
      path: '/backgammon/new'
      fullPath: '/backgammon/new'
      preLoaderRoute: typeof BackgammonNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgammon/local': {
      id: '/backgammon/local'
      path: '/backgammon/local'
      fullPath: '/backgammon/local'
      preLoaderRoute: typeof BackgammonLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgammon/$sessionId': {
      id: '/backgammon/$sessionId'
      path: '/backgammon/$sessionId'
      fullPath: '/backgammon/$sessionId'
      preLoaderRoute: typeof BackgammonSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$sessionId/play': {
      id: '/quiz/$sessionId/play'
      path: '/quiz/$sessionId/play'
      fullPath: '/quiz/$sessionId/play'
      preLoaderRoute: typeof QuizSessionIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$sessionId/host': {
      id: '/quiz/$sessionId/host'
      path: '/quiz/$sessionId/host'
      fullPath: '/quiz/$sessionId/host'
      preLoaderRoute: typeof QuizSessionIdHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hitster/$sessionId/play': {
      id: '/hitster/$sessionId/play'
      path: '/hitster/$sessionId/play'
      fullPath: '/hitster/$sessionId/play'
      preLoaderRoute: typeof HitsterSessionIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hitster/$sessionId/host': {
      id: '/hitster/$sessionId/host'
      path: '/hitster/$sessionId/host'
      fullPath: '/hitster/$sessionId/host'
      preLoaderRoute: typeof HitsterSessionIdHostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  BackgammonSessionIdRoute: BackgammonSessionIdRoute,
  BackgammonLocalRoute: BackgammonLocalRoute,
  BackgammonNewRoute: BackgammonNewRoute,
  ChessSessionIdRoute: ChessSessionIdRoute,
  ChessNewRoute: ChessNewRoute,
  ConnectFourSessionIdRoute: ConnectFourSessionIdRoute,
  ConnectFourNewRoute: ConnectFourNewRoute,
  GamesGameTypeRoute: GamesGameTypeRoute,
  HitsterNewRoute: HitsterNewRoute,
  QuizNewRoute: QuizNewRoute,
  SignalWordsSessionIdRoute: SignalWordsSessionIdRoute,
  SignalWordsNewRoute: SignalWordsNewRoute,
  SudokuSessionIdRoute: SudokuSessionIdRoute,
  SudokuNewRoute: SudokuNewRoute,
  SudokuScanRoute: SudokuScanRoute,
  WordLinksPuzzleIdRoute: WordLinksPuzzleIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  WordLinksIndexRoute: WordLinksIndexRoute,
  HitsterSessionIdHostRoute: HitsterSessionIdHostRoute,
  HitsterSessionIdPlayRoute: HitsterSessionIdPlayRoute,
  QuizSessionIdHostRoute: QuizSessionIdHostRoute,
  QuizSessionIdPlayRoute: QuizSessionIdPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
