/** Sudoku + binary-puzzle UI chrome. Puzzle digits, cell notation like
 * "R1C1", and hint explanations generated by sudoku-hints.ts are numeric or
 * notation content, not translatable prose, and are never routed through
 * message keys. */
export const sudoku = {
	difficulty: {
		easy: "Easy",
		medium: "Medium",
		hard: "Hard",
		expert: "Expert",
	},
	variant: {
		classic: "Classic",
		killer: "Killer",
		binary: "Binary",
	},
	board: {
		cellLabel: "Row {row} column {col}",
	},
	keypad: {
		modeDigit: "Digit",
		modeCorner: "Corner",
		modeCenter: "Center",
		modeColor: "Color",
		colorAriaLabel: "Color {number}",
		undo: "Undo",
		redo: "Redo",
		erase: "Erase",
		hint: "Hint",
	},
	game: {
		renameTooltip: "Rename this puzzle",
		importedFallback: "Imported",
		scannedLabel: "scanned",
		solvedTitle: "Solved! 🎉",
		completedIn: "Completed in {time}.",
		startAnotherPuzzle: "Start another puzzle",
		pausedOverlay: "Paused — tap to resume",
		pauseButton: "Pause",
		hintFallbackTitle: "Hint",
		dismissHint: "Dismiss",
		tellMeMore: "Tell me more",
		autoCleanupLabel: "Auto-remove notes when a digit is placed",
		restartConfirm:
			"Restart this puzzle? Your progress is kept in undo history.",
		keyboardHelp:
			"Keyboard: 1-9 digits · Shift+digit corner note · Ctrl+digit center note · Space cycles mode · Ctrl+Z/Y undo/redo · arrows move",
	},
	binary: {
		dimensions: "Binary {size}×{size}",
		restartConfirm: "Restart this puzzle?",
		instructions:
			"Tap a cell to cycle 0 → 1 → empty. No three alike in a row, equal 0s and 1s per line, no duplicate lines.",
		remainingCells: {
			one: "{count} cell to go",
			other: "{count} cells to go",
		},
	},
	scan: {
		pageHeading: "Scan a paper puzzle",
		couldNotReadImage: "Could not read the image",
		recognitionFailed: "Recognition failed",
		preparingImage: "Preparing image...",
		readingCells: "Reading cells {done}/{total}...",
		correctedGridAlt: "Corrected sudoku grid",
		uploadInstructions:
			"Photograph or upload a printed sudoku — including one you already started solving on paper. You will verify the recognized grid before playing.",
		takePhoto: "Take a photo",
		uploadImage: "Upload an image",
		dragCorners: "Drag the four handles onto the corners of the sudoku grid.",
		uploadedImageAlt: "Uploaded sudoku",
		readGrid: "Read this grid",
		scannedImageLabel: "Scanned image",
		recognizedGridLabel: "Recognized grid — tap a cell to correct it",
		lowConfidenceHighlighted: {
			one: "{count} low-confidence cell highlighted in amber.",
			other: "{count} low-confidence cells highlighted in amber.",
		},
		allConfident:
			"All recognitions look confident — still, double-check before starting.",
		cellLabel: "Cell R{row}C{col}",
		lowConfidenceBadge: "low confidence",
		cellTypeGiven: "Given",
		cellTypeUserDigit: "Your digit",
		cellTypeCornerNotes: "Corner notes",
		cellTypeCenterNotes: "Center notes",
		cellTypeEmpty: "Empty",
		clearCell: "Clear cell",
		previewLabel: "Preview — exactly how the puzzle will start",
		multipleSolutionsWarning:
			"The givens allow more than one solution. You can still play, but consider double-checking for missed digits.",
		uniqueSolution: "Looks good: the givens define a unique solution.",
		startOver: "Start over",
		creatingPuzzle: "Creating puzzle...",
		confirmAndPlay: "Confirm and play",
		couldNotCreateSession: "Could not create session",
	},
	newGame: {
		heading: "Start a puzzle",
		intro:
			"Pick a difficulty and play solo. Your progress saves automatically, and you can keep several puzzles going at once.",
		nameLabel: "Puzzle name (optional)",
		namePlaceholder: "Auto-named by level and time",
		gameTypeLegend: "Game type",
		variantBlurbClassic: "The familiar 9×9 grid",
		variantBlurbKiller: "Cages must add up to their sum",
		variantBlurbBinary: "Fill the grid with 0s and 1s",
		difficultyBlurbs: {
			easy: {
				classic: "Plenty of clues, gentle start",
				killer: "Many givens, small cages",
				binary: "6×6 grid, gentle start",
			},
			medium: {
				classic: "Singles and simple pairs",
				killer: "Fewer givens, lean on the sums",
				binary: "8×8 grid",
			},
			hard: {
				classic: "Pointing pairs and reductions",
				killer: "A handful of givens",
				binary: "10×10 grid",
			},
			expert: {
				classic: "Sparse clues, deep scanning",
				killer: "Cages only — no givens",
				binary: "10×10, sparse clues",
			},
		},
		generating: "Generating...",
		scanInstead: "Scan a paper puzzle instead",
		yourPuzzles: "Your puzzles",
		removeFromList: "Remove {title} from this list",
		couldNotStart: "Could not start the puzzle",
	},
	session: {
		loadingPuzzle: "Loading puzzle...",
		puzzleNotFound: "Puzzle not found.",
	},
};
